# -*- coding: utf-8 -*-
"""DT (Breast Cancer - Feature names).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jRTyiaN-BBE-zyUkbWSyuSjTD2_yZ-oZ
"""

from sklearn import tree
from sklearn import datasets

dataset = datasets.load_breast_cancer()

target_names = dataset.target_names
feature_names = dataset.feature_names

X = dataset.data
Y = dataset.target


clf = tree.DecisionTreeClassifier()

clf = clf.fit(X, Y)

#tree.plot_tree(clf)

#plotar de forma mais elaborada
import graphviz
dot_data = tree.export_graphviz(clf, out_file=None, filled=True, rounded=True, impurity=True,
                                feature_names = feature_names,
                                class_names = target_names
)
graph = graphviz.Source(dot_data)
graph.render("graph")

# export in text format
r = tree.export_text(clf)
print('\n'+r)

dataset.feature_names