# -*- coding: utf-8 -*-
"""DT (Breast Cancer).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1epoim_CSqszHAg3-6XIJaewW837Es9yN
"""

from sklearn import tree
from sklearn import datasets
#import ipdb

dataset = datasets.load_breast_cancer()

X = dataset.data
Y = dataset.target

clf = tree.DecisionTreeClassifier()
clf.fit(X, Y)

#tree.plot_tree(clf)

#plotar de forma mais elaborada
import graphviz
dot_data = tree.export_graphviz(clf, out_file=None, filled=True, rounded=True, impurity=True)
graph = graphviz.Source(dot_data)
graph.render("graph")

# export in text format
r = tree.export_text(clf)
print('\n'+r)