# -*- coding: utf-8 -*-
"""DT (Accuracy).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EmRDuyFY3ZycRrJwLyINQRKPRhAUZejC
"""

from sklearn import tree
from sklearn import datasets
from sklearn.metrics import accuracy_score

dataset = datasets.load_breast_cancer()

X = dataset.data
Y = dataset.target

target_names = dataset.target_names
feature_names = dataset.feature_names

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

predictedY = clf.predict(X)

accuracy = accuracy_score(Y, predictedY)
print(accuracy)

# export in graphical format
# import graphviz
# dot_data = tree.export_graphviz(clf, out_file=None, filled=False, rounded=True, impurity=True, class_names=target_names, feature_names=feature_names)

# graph = graphviz.Source(dot_data)
# graph.render("graph")

# export in text format
#r = tree.export_text(clf)

#print('\n'+r)