# -*- coding: utf-8 -*-
"""DT-intro_plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhVToxvc8Xwhk16XplesWZRoERU5HqSL
"""

from sklearn import tree

X = [[0,0],[0,1],[1,0],[1,1] ]
Y = [0,1,1,0]

clf = tree.DecisionTreeClassifier()

clf.fit(X, Y)

clf.predict([[0,0]])


# export in text format
r = tree.export_text(clf)
print('\n'+r)



tree.plot_tree(clf)

"""Agora, faremos o mesmo, mas usando o Graphviz"""

from sklearn import tree

X = [[0,0],[0,1],[1,0],[1,1] ]
Y = [0,1,1,0]

clf = tree.DecisionTreeClassifier()

clf.fit(X, Y)

#plotar de forma mais elaborada
import graphviz
dot_data = tree.export_graphviz(clf, out_file=None, filled=True, rounded=True, impurity=True)
graph = graphviz.Source(dot_data)
graph.render("graph")