# -*- coding: utf-8 -*-
"""DT-intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJSjakTFe81dejc2xvScGVCj7lUm_gxy
"""

from sklearn import tree

X = [[0,0],[0,1],[1,0],[1,1] ]
Y = [0,1,1,0]

clf = tree.DecisionTreeClassifier()

clf.fit(X, Y)

clf.predict_proba([[0,0]])