# -*- coding: utf-8 -*-
"""kmeans_teste_inicial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1al3axBwje9DY0LmefzBdMmBo8LgYt4r3

# K-means (teste inicial)
"""

import os
#import ipdb; # ipdb.set_trace()

import numpy as np

from sklearn.cluster import KMeans


#X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0]])
X = np.array([[1, 3], [1, 4], [1, 0], [10, 1], [10, 4], [10, 0]])
#kmeans = KMeans(n_clusters=2).fit(X)
kmeans = KMeans(n_clusters=3)
kmeans.fit(X)

# print the results for the training data
print(kmeans.labels_)

# predict for new data
print(kmeans.predict([[10, 4.5]]))
#print(kmeans.predict([[0,0], [12,3]]))

# show centers
print(kmeans.cluster_centers_)