# -*- coding: utf-8 -*-
"""KNN_parte1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a1kBOLSVjK_E3GbXWP6HBv-F-8CRYZjo

# KNN - Parte 1 (testes iniciais)
"""

from sklearn import neighbors

X = [ [2.0,1.5,1.0], [1.0,1.0,0.5], [1.0,3.0,1.5], [0.8,2.2,0.7], [3.0,1.0,0.2], [0.4,2.0,1.7], [1.2,1.2,1.5]  ]
Y = [ 1, 0, 1, 0, 1, 1, 1 ]


clf = neighbors.KNeighborsClassifier(n_neighbors=3) #k =1, 3, 5, 7
clf.fit(X, Y)
print(clf.predict([[0.9, 1.1, 0.5]]))
print(clf.predict_proba([[0.9, 1.1, 0.5]]))